"""Added stringnote

Revision ID: a69c7a768777
Revises: c3f1f041ee47
Create Date: 2020-04-04 16:59:30.427663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69c7a768777'
down_revision = 'c3f1f041ee47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('string-notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('keys', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('accidental', sa.String(), nullable=True),
    sa.Column('dot', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_string-notes_bar_id'), 'string-notes', ['bar_id'], unique=False)
    op.add_column('bars', sa.Column('clef', sa.String(), nullable=True))
    op.add_column('bars', sa.Column('time_signature', sa.String(), nullable=True))
    op.create_foreign_key(None, 'bars', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bars', type_='foreignkey')
    op.drop_column('bars', 'time_signature')
    op.drop_column('bars', 'clef')
    op.drop_index(op.f('ix_string-notes_bar_id'), table_name='string-notes')
    op.drop_table('string-notes')
    # ### end Alembic commands ###
