"""add json_record to string_note

Revision ID: a830d89d5eaf
Revises: 3d5559e62110
Create Date: 2020-04-18 18:13:11.785371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_jsonfield

# revision identifiers, used by Alembic.
revision = 'a830d89d5eaf'
down_revision = '3d5559e62110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('string_notes') as batch_tbl:
        batch_tbl.add_column(sa.Column('json_record', sqlalchemy_jsonfield.jsonfield.JSONField(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('string_notes') as batch_tbl:
        batch_tbl.drop_column('json_record')
    # ### end Alembic commands ###
