"""changed email
Revision ID: c3f1f041ee47
Revises: e8a33f80703e
Create Date: 2020-03-28 23:19:28.402990
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f1f041ee47'
down_revision = 'e8a33f80703e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=51), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_foreign_key(None, 'bars', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bars', type_='foreignkey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
# ### end Alembic commands ###