"""edit column in bars

Revision ID: ffb9da1c446e
Revises: 24c0cd43ff6a
Create Date: 2020-03-28 17:56:56.179893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb9da1c446e'
down_revision = '24c0cd43ff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bars', sa.Column('track_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bars_track_id'), 'bars', ['track_id'], unique=False)
    op.create_foreign_key(None, 'bars', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'])
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.create_foreign_key(None, 'lines', 'bars', ['position_5'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_3'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_8'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_6'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_7'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_2'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lines', 'bars', ['position_4'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bars', type_='foreignkey')
    op.drop_index(op.f('ix_bars_track_id'), table_name='bars')
    op.drop_column('bars', 'track_id')
    # ### end Alembic commands ###
